FROM python:3.6-stretch

WORKDIR /redbot

ADD . /redbot

RUN python setup.py install
RUN pip3 install -r requirements.txt
RUN echo "REDIS_HOST = 'redis'" > redbot/settings_local.py

CMD ["python", "redbot-web"]